Add setting customizable rsync exit code success

diff --git a/cfgbackup b/cfgbackup
--- a/cfgbackup
+++ b/cfgbackup
@@ -21,7 +21,7 @@
 # SOFTWARE.
 ################################################################################
 
-VERSION=0.4.3
+VERSION=0.4.4
 
 #######################################
 # MISC HELPER FUNCTIONS
@@ -341,6 +341,7 @@ default_config() {
     CONFIG[TARGET_DIR]=
     CONFIG[RSYNC_FLAGS]=
     CONFIG[NOTIFY_RSYNC_FLAGS]=-O
+    CONFIG[RSYNC_EXIT_CODE_SUCCESS]=24
     CONFIG[BACKUP_TYPE]=
     CONFIG[ROTATE_SUBDIR]=backup-NUM1
     CONFIG[RUNNING_DIRNAME]=backup-running
@@ -388,6 +389,20 @@ config_param_exists() {
 }
 
 ###############################
+# Check if passed value is a successful rsync exit code, as defined by the config settings
+##  $1 -> Exit code to check
+## Returns 0 if exit code was a success; 1 otherwise
+config_rsync_exit_successful() {
+    BIFS="$IFS"
+    IFS=', ' read -r -a SUCCESS_CODES <<< "${CONFIG[RSYNC_EXIT_CODE_SUCCESS]}"
+    SUCCESS_CODES+=("0")
+    array_contains SUCCESS_CODES "$1"
+    SUCCESS_EXIT=$?
+    IFS="$BIFS"
+    return $SUCCESS_EXIT
+}
+
+###############################
 ## Parse config file given
 ## Returns 0 on success, 1 on error
 ## Any errors will be in PARSE_ERRORS
@@ -403,8 +418,8 @@ parse_config() {
         for KEY in "${!CONFIG[@]}"; do
             # Get variable values from config file
             CONFIG_VALUE=$(config_param_get $CONFIG_FILE $KEY)
-            # If key is NOTIFY_RSYNC_FLAGS, allow for setting value to empty
-            if [[ $KEY == "NOTIFY_RSYNC_FLAGS" ]] && config_param_exists $CONFIG_FILE $KEY; then
+            # If key is NOTIFY_RSYNC_FLAGS or RSYNC_EXIT_CODE_SUCCESS, allow for setting value to empty
+            if [[ $KEY == "NOTIFY_RSYNC_FLAGS" || $KEY == "RSYNC_EXIT_CODE_SUCCESS" ]] && config_param_exists $CONFIG_FILE $KEY; then
                 : # do nothing
             # If value is empty, leave as default
             elif [[ $CONFIG_VALUE == "" ]]; then
@@ -1266,9 +1281,9 @@ runjob_rotation() {
     RSYNC_COMMAND="$RSYNC_COMMAND >> ${LOG_FILE} 2>&1"
     eval $RSYNC_COMMAND
     RSYNC_EXIT=$?
-    # On any error (except 24), send email report
-    if [[ $RSYNC_EXIT -gt 0 && $RSYNC_EXIT -ne 24 ]]; then
-        log_entry "| Rsync command exited with code: $RSYNC_EXIT"
+    log_entry "| Rsync command exited with code: $RSYNC_EXIT"
+    # On any error, send email report
+    if ! config_rsync_exit_successful $RSYNC_EXIT; then
         command_runscript FAILED_SCRIPT
         mailer_rsync_exit $RSYNC_EXIT
         return
@@ -1450,8 +1465,8 @@ runjob_mirror() {
             RSYNC_COMMAND="$RSYNC_COMMAND >> ${LOG_FILE} 2>&1"
             eval $RSYNC_COMMAND
             RSYNC_EXIT=$?
-            if [[ $RSYNC_EXIT -gt 0 && $RSYNC_EXIT -ne 24 ]]; then
-                log_entry "| Rsync command exited with code: $RSYNC_EXIT"
+            log_entry "| Rsync command exited with code: $RSYNC_EXIT"
+            if ! config_rsync_exit_successful $RSYNC_EXIT; then
                 MIRROR_FAILURE=1
             fi
             rm $SRC_FILES_REMOVED_FILE
@@ -1469,8 +1484,8 @@ runjob_mirror() {
             RSYNC_COMMAND="$RSYNC_COMMAND >> ${LOG_FILE} 2>&1"
             eval $RSYNC_COMMAND
             RSYNC_EXIT=$?
-            if [[ $RSYNC_EXIT -gt 0 && $RSYNC_EXIT -ne 24 ]]; then
-                log_entry "| Rsync command exited with code: $RSYNC_EXIT"
+            log_entry "| Rsync command exited with code: $RSYNC_EXIT"
+            if ! config_rsync_exit_successful $RSYNC_EXIT; then
                 MIRROR_FAILURE=1
             fi
             rm $TGT_FILES_REMOVED_FILE
@@ -1492,8 +1507,8 @@ runjob_mirror() {
             RSYNC_COMMAND="$RSYNC_COMMAND >> ${LOG_FILE} 2>&1"
             eval $RSYNC_COMMAND
             RSYNC_EXIT=$?
-            if [[ $RSYNC_EXIT -gt 0 && $RSYNC_EXIT -ne 24 ]]; then
-                log_entry "| Rsync command exited with code: $RSYNC_EXIT"
+            log_entry "| Rsync command exited with code: $RSYNC_EXIT"
+            if ! config_rsync_exit_successful $RSYNC_EXIT; then
                 MIRROR_FAILURE=1
             fi
         fi
@@ -1508,8 +1523,8 @@ runjob_mirror() {
             RSYNC_COMMAND="$RSYNC_COMMAND >> ${LOG_FILE} 2>&1"
             eval $RSYNC_COMMAND
             RSYNC_EXIT=$?
-            if [[ $RSYNC_EXIT -gt 0 && $RSYNC_EXIT -ne 24 ]]; then
-                log_entry "| Rsync command exited with code: $RSYNC_EXIT"
+            log_entry "| Rsync command exited with code: $RSYNC_EXIT"
+            if ! config_rsync_exit_successful $RSYNC_EXIT; then
                 MIRROR_FAILURE=1
             fi
         fi
@@ -1719,7 +1734,7 @@ runhelp() {
     echo "  run     - Run the backup according to the config file provided."
     echo "  reset   - Resets partially completed or failed backups. This will"
     echo "            abort a currently running backup."
-    echo "  accept  - Accepts as partially completed or failed backup as"
+    echo "  accept  - Accepts a partially completed or failed backup as"
     echo "            successful. This will abort a currently running backup."
     echo ""
     echo "cfgbackup v${VERSION}"
